version: '2'
services:
    climatefinance-app:
        image: climatefinance
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://climatefinance-postgresql:5432/climatefinance
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=climatefinance-elasticsearch:9300
        ports:
            - 8080:8080
    climatefinance-postgresql:
        extends:
            file: postgresql.yml
            service: climatefinance-postgresql
    climatefinance-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: climatefinance-elasticsearch
